### ISSUE TITLE
Store pointer expansion status for each workspace

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#139]

**Comment by stuhlmueller** [comment]
Consider whether it's possible to simultaneously change our setup such that pointers that are not visible do not get loaded. This is the main way I see for speeding up the system, but I assume that it's a big change.

**Comment by stuhlmueller** [comment]
Once we store pointer expansion status, we should update the staleness computation s.t. edits to an exported text mark all workspaces as stale that import the corresponding pointer and have it expanded.

**Comment by zjmiller** [comment]
We now store locked/unlocked status.
