### ISSUE TITLE
Pressing backspace to the right of exported pointer doesn't do anything

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#156]
I pressed backspace many times here:

![2018-08-30 16-50-31 2018-08-30 16_51_10](https://user-images.githubusercontent.com/382515/44885342-3713dd80-ac75-11e8-87c5-88a386684c5c.gif)

**Comment by zjmiller** [comment]
This is expected behavior. You have to remove a pointer by hovering over it and clicking on remove pointer, backspace just empties it.

**Comment by zjmiller** [comment]
Oops didn't mean to close this.
