### ISSUE TITLE
Cursor sometimes ends up inside bracket after pointer creation

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#174]
![pointers-question](https://user-images.githubusercontent.com/382515/45850156-d9116d80-bce9-11e8-87c8-26d5b7cf2109.gif)

1. After typing the closing bracket, the pointer ended up in the wrong place (inside the square brackets instead of outside).
2. It was impossible to delete the pointer.

**Comment by zjmiller** [comment]
With respect to 1, sometimes the cursor ends up in the position you've described, and sometimes it ends up (correctly) outside the brackets. This makes me think there must be some sort of race condition in the new question form that doesn't exist in the other blocks. I'll look into it.

As far as deleting the pointer goes, I think this is the behavior we want? Currently, you have to hover over it and click the "Remove Pointer" button to delete the pointer itself.

**Comment by stuhlmueller** [comment]
> As far as deleting the pointer goes, I think this is the behavior we want? Currently, you have to hover over it and click the "Remove Pointer" button to delete the pointer itself.

Good point. Let's keep it as is for now (but I think the fact that I forgot about this behavior and made an issue without remembering it means that the UI isn't entirely intuitive).

**Comment by stuhlmueller** [comment]
The cursor now ends up pretty reliably inside of the outermost bracket for me.
