### ISSUE TITLE
Add instructions to app

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#178]
From Slack:

> things to know:
> 1. just click on “get next workspace” in the nav bar, make changes if you see any way to improve the workspace it gives you, then click on next workspace again, repeat
> 2. make pointers using square brackets, expand pointers by clicking on them, refer to pointers by typing $[number], e.g. $1
> 3. see my work-in-progress instructions for H: https://docs.google.com/document/d/1wx0QoNP-KRpRAI5RgK3A_VAL7vNMZ2lt-VDLvPlB5aI/edit?usp=sharing

Probably needs more work to be comprehensible.

**Comment by zjmiller** [comment]
Seems superseded by #208. Though would probably be useful to distinguish between an initial tutorial and a help page users can use if they have a specific question.
