### ISSUE TITLE
People get logged out much more frequently than they should

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#244]

**Comment by stuhlmueller** [comment]
I changed the token validity time on auth0 from 10 hours to 14 days (but people got logged out after less than an hour, so this setting was probably not the cause).

**Comment by cnorthwood** [comment]
I believe #427 will address this (by periodically refreshing the access token), however it requires a change of config on the Auth0 side

> Remember to add the URL where the authorization request originates from, to the Allowed Web Origins list of your Auth0 application in the Dashboard under your application's Settings.

Currently refreshing gives me an error, so I haven't been able to test the fix

**Comment by zjmiller** [comment]
Addressed in #527
