### ISSUE TITLE
Consider adding Redis or similar

### ISSUE THREAD

**Issue by zjmiller** [oughtinc/mosaic#309]
Currently, some data structures are just represented as JS variables. 

E.g., the automated scheduler stores all of its scheduling history info as JS arrays, objects, maps, etc., and so won't easily scale, won't persist across server crashes/restarts, and isn't stored in a way that would allow future analysis.

The other potential thing that we might want to move to Redis is the oracle mode global flag.

**Comment by stuhlmueller** [comment]
What's the advantage over storing these things in postgres?

**Comment by zjmiller** [comment]
Went with Postgres for now.
