### ISSUE TITLE
Can't remove empty pointers

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#319]
![remove-empty-pointer](https://user-images.githubusercontent.com/382515/50302011-ac323b00-043d-11e9-9307-907a4efa5f4f.gif)

**Comment by stuhlmueller** [comment]
This only happens under some circumstances (don't know which), not always.

**Comment by zjmiller** [comment]
I'm hoping this was taken care of by the big copy-paste rework (which resolved some bugs very similar to this one). If we encounter this issue open, I'll re-open.
