### ISSUE TITLE
Email/password signup failed

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#326]
![screen shot 2018-12-29 at 11 07 38 am](https://user-images.githubusercontent.com/382515/50536913-0330c200-0b5a-11e9-9ea9-aeadd8a6b0bd.png)

**Comment by zjmiller** [comment]
Every time this has happened to me, it's been because I've navigated to the login/signup form in a non-standard way (usually by pressing back). Auth0 seems to care a lot about you navigate to these forms.
