### ISSUE TITLE
Create issues from experiment feedback documents

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#332]

**Comment by zjmiller** [comment]
I didn't include the following

- (5) (Too up in the air) Restructure factored evaluation to allow malicious oracle to ask three root-level questions, honest oracle answers all of them, and finally malicious oracle sees all of these three honest responses and chooses one to engage with and the others are dismissed.
- (6) (Needs to be made more precise) "Figure out a better and more restrictive way to limit the user’s question-asking resources".
- (10) (Needs to be made more precise) "Do something about lazy pointers".
