### ISSUE TITLE
Unlocked pointer shows as locked while logged out

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#361]
Compare pointer $5 when logged in:

![image](https://user-images.githubusercontent.com/16952006/52822404-71780800-3066-11e9-9309-1130b304a790.png)

to logged out:

![image](https://user-images.githubusercontent.com/16952006/52822421-79d04300-3066-11e9-94e6-0af622e284d8.png)

to logged out after clicking on $5:

![image](https://user-images.githubusercontent.com/16952006/52822433-85236e80-3066-11e9-831e-44dc020fd03c.png)

**Comment by brachbach** [comment]
A pretty minor issue but brought it up b/c:
- it means that we should prob advise people to always log in to view workspaces
- I thought it could possibly be related to some deeper problem
- maybe we should just make it impossible to view workspaces while logged out, to avoid this and related problems

**Comment by zjmiller** [comment]
Thanks for noticing this. It's actually more related to the fact that exports are displayed as imports when no one is logged in. This feature (displaying exports as imports when no one is logged in) is an old one (predates my joining the project), and I'm not sure what the motivation is. To me it makes more sense to always show exports as exports, even if no one is logged in. It seems like important information is lost if exports are displayed as imports. Unless someone objects, I'll change things so exports are displayed as exports (this will also resolve this issue). Of course, if no one is logged in, the export will be un-editable, just like the rest of the workspace content.
