### ISSUE TITLE
Functionality to expand/collapse all unlocked pointers

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#362]
I've sometimes wished that there were a way to expand or collapse all pointers in a workspace.

Maybe a keyboard shortcut only so it doesn't clutter the UI.

I think what I want is for "expand all" to expand recursively down through multiple levels of nested pointers, as much as possible w/o getting stuck in cycles

But I'd also be pretty happy if it just expanded all pointers one level at a time

I'd say not high pri

**Comment by zjmiller** [comment]
In #541
