### ISSUE TITLE
Evaluate alternatives for Logrocket

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#387]
Issues with Logrocket:
- Can't download videos
- Recordings expire quickly
- Difficult to organize videos

Potential alternatives:
- FullStory
- HotJar

**Comment by cnorthwood** [comment]
Neither HotJar nor FullStory allow downloading of recordings, but FullStory has 30 day retention and Hotjar 1 year retention (although only 300 recordings). As far as I can tell only FullStory gives a way of associating sessions with usernames, so I'd recommend that, if the retention is useful
