### ISSUE TITLE
Simplify UX for judge to choose between the two answers

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#498]
Instead of having to type "A1 $1" or "A2 $2", there should be two buttons, one for each answer, and the judge should be able to just click on one or the other

**Comment by zjmiller** [comment]
I think this is a great idea. 

I'm not sure how to combine this with the ability to throw an error with `X: ...`, which requires the judge can pass text content up the tree (as opposed to merely passing a decision up the tree). Are we thinking of removing this option for judges?

**Comment by stuhlmueller** [comment]
I think it's fine to remove that option. (We should keep open the possibility that we'll want to add more buttons in the future, e.g. a button "Can't tell" that then requests a reason from the user.)

**Comment by zjmiller** [comment]
Included in #534
