### ISSUE TITLE
Give each workspace a reference number/letter

### ISSUE THREAD

**Issue by zjmiller** [oughtinc/mosaic#505]
To make it easier to refer to.

**Comment by zjmiller** [comment]
> We could also use these identifiers to make shorter workspace URLs

**Comment by stuhlmueller** [comment]
In general we should have shorter URLs for everything, including experiments. There is no reason to use full UUIDs in URLs.

**Comment by Mati-Roy** [comment]
This has been done, right? I don't think I can close the issue myself though
