### ISSUE TITLE
Make it easier for experimenter to create many similar top-level questions

### ISSUE THREAD

**Issue by zjmiller** [oughtinc/mosaic#507]
Ideally via API endpoint.

**Comment by zjmiller** [comment]
A lot of elaboration in _**Feedback from Mosaic internal experiment - Apr 9, 2019**_. Won't paste here.

**Comment by zjmiller** [comment]
Subsumed by #517

**Comment by Mati-Roy** [comment]
with the API, that's now easy enough, right?
