### ISSUE TITLE
Add Intercom widget (https://www.intercom.com/) or similar to Mosaic to make it easier for participants to get in touch with us

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#588]
- this would just be to test this out -- we're uncertain that it's actually a good idea to make it this easy to get in touch with Ben R/experiment runners
- note that our lag team in responding would often be like 12 hrs, so we need to choose something that makes sense for that sort of lag time (e.g. email notifications if there's a long lag)
- unclear how important this is

**Comment by brachbach** [comment]
@stuhlmueller I think the first step here is to figure out whether Intercom or something else is the best system -- want to look into that?

(I'm not too excited about this on the whole, so not too excited about looking into it)

**Comment by stuhlmueller** [comment]
When I looked into this for ThinkAgain, Intercom seemed best.

**Comment by andrewschreiber** [comment]
According to Zak, Ozzie expects this would take 1-2 days.

**Comment by brachbach** [comment]
Note that we expect to have very delayed responses to people using Intercom (up to like a day)

**Comment by andrewschreiber** [comment]
Do we have a master email that I can register the Intercom account under? Note: there is no free plan, so would need the Brex info to move forward with a subscription (even the 14 day free trial). https://www.intercom.com/pricing. 

Meanwhile I have a basic setup running locally:

![image](https://user-images.githubusercontent.com/1892071/62523823-759d0b00-b7e9-11e9-94df-5f4813a46cc6.png)

**Comment by brachbach** [comment]
awesome!

master email is where we'd want messages from Intercom to go? If so, it's experiments@ought.org.
