### ISSUE TITLE
API bug: when creating trees without top-level answers provided, top-level honest workspace not stale

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#594]
Of course, the next workspace that needs work should always be stale. 

Worth testing this for all possible sets of info provided via API -- just top-level Q, also honest top-level answer, also malicious top-level answer

**Comment by andrewschreiber** [comment]
Getting started here. @brachbach does the 3 cases you mentioned: 
- [ ] just top-level Q
- [ ] honest top-level answer
- [ ] malicious top-level answer

encapsulate all possible sets?

**Comment by brachbach** [comment]
yep!

TBC, the possibilities are actually:
- top level Q
- top level Q + honest top-level A
- top level Q + honest top-level A + malicious top-level A

**Comment by andrewschreiber** [comment]
Still learning the stale system. It looks like workspaces and their honest/malicious children each can be stale or not. Call them W, HC, and MC, respectively. I'm assuming W corresponds to Q, HC to honest, and MC to malicious.

I've found the place in the codebase where staleness is determined (`bulkCreateExperiments` in `server/lib/schema/index.ts`).

I'm trying to figure out who (W, HC, MC) should be stale, under what circumstances. It seems that the behavior that you want is when a workspace is created without an honest answer, the HC should be stale. So is it something like:

top level Q -> W is stale, HC & MC not-stale
top level Q + honest top-level A -> MC stale, W & HC not-stale
top level Q + honest top-level A + malicious top-level A -> W & MC & HC not-stale.

But what about:
top level Q + malicious top-level A? I guess HC stale, W & MC not-stale

Is this accurate?

**Comment by zjmiller** [comment]
I think the simplest way to do it would be to make the leaf workspace stale and the ancestors not stale. So if there's no honest answer, then honest workspace stale. If there's an honest answer, then malicious workspace stale. If there are both answers, then the judge workspace stale. In all cases, the other workspaces not stale.

**Comment by andrewschreiber** [comment]
Current behavior on master, created using a new CSV that runs every configuration:

**Top-level Q only** ❌
-> Workspace 50 should be stale
![image](https://user-images.githubusercontent.com/1892071/62392485-67669a80-b51c-11e9-8c92-8f78d7d77c65.png)

**Top-level Q + honest answer**❌
-> Workspace 53 should be stale
![image](https://user-images.githubusercontent.com/1892071/62392532-882ef000-b51c-11e9-85f4-ebec720e8045.png)


**Top-level Q + honest answer + malicious answer** ✅
-> Workspace 57 is correctly stale
![image](https://user-images.githubusercontent.com/1892071/62392548-8fee9480-b51c-11e9-8bfc-940482230b36.png)

**Comment by zjmiller** [comment]
What's going on with the `text: undefined`? Is that something we should be worried about? Could I see the CSV file?

**Comment by andrewschreiber** [comment]
@zjmiller Yeah that does look like strange behavior from the scratchpad. I looked into it and it comes from the `mosaic-api-scripts` line here https://github.com/oughtinc/mosaic-api-scripts/blob/master/createExperiments/getExperimentData.ts#L12
