### ISSUE TITLE
Rename "Needs more work" button to something else

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#620]
Being confused by the name of the button was one of the top complaints mentioned by experiment participants when I asked them for feedback

The button is currently mostly used:
1. in training experiments in the case where someone doesn't need more practice with a particular role/workspace and wants to leave it for someone else
2. when someone feels too contaminated to complete a workspace
3. when someone thinks that one of the other honest/malicious experts on the tree would do a better job on the workspace than they would

I'm thinking good names could be:
1. "Pass off workspace"
2. "Skip workspace"
3. "Save and pass"

"Save and pass" is probably my favorite, followed by "Skip workspace"

**Comment by brachbach** [comment]
I'll also plan to add more explanation of this button to the training materials

**Comment by Mati-Roy** [comment]
Personally, "Save and pass" would make me think it's okay for me to work on it a bit, then saving the workspace and passing it to someone else, whereas "Skip workspace" would make me think I cannot work on it if I'm going to skip it.

**Comment by brachbach** [comment]
@Mati-Roy good point. We actually mean "I cannot [or at least should not] work on it if I'm going to skip it."

**Comment by derekelkins** [comment]
Do we want to encourage use-case 3, i.e. "I think someone else would do better"? My impression is that we'd want to strongly discourage that.

**Comment by brachbach** [comment]
=> "Skip workspace"
