### ISSUE TITLE
Always give experts easy access to the text

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#626]
Not an issue for malicious expert since they can just get the link from the full tree view

But honest expert is stuck if the judge neglects to pass the pointer link

(Both in theory, and now that each tree has many honest experts and each participant is honest expert on many trees, also in practice.)

Strategically, there's no time when the judge would ever intentionally not provide the link (since the malicious expert can always get it from the full tree view, so not passing it just asymmetrically disfavors the honest expert)

**Comment by zjmiller** [comment]
Technically, the easiest approach might be including the root workspace's scratchpad (as read only) in every expert workspace. Does that sound like it would work? (Would probably take fewer than 8 hrs w/ this approach.)

**Comment by brachbach** [comment]
hmm... yeah I think that'd work, becuase it's easy to set the contents of the root scratchpad via the API, right?

**Comment by andrewschreiber** [comment]
Notes from conversation with Zak:
- Will need to add pointers from this into pointer system (can do last)
- Can export content with green export pointer, can import with blue import pointer. Look into AvailablePointers, EpisodeShow.
- Make sure AvailablePointers have pointer to root workspace
