### ISSUE TITLE
"Declining to challenge" top non-root malicious makes root get scheduled

### ISSUE THREAD

**Issue by zjmiller** [oughtinc/mosaic#659]
If a malicious expert declines to challenge at the first opportunity to do (ending the tree before a single judge workspace), this reschedules the root workspace.

To fix we need `declineToChallenge` mutation to check for whether the grandparent of the malicious workspace is root or not.

**Comment by brachbach** [comment]
@zjmiller -- how bad a bug is this, for both vanilla FE and MIB?

(Asking because it seems maybe quite bad from what's written here, and I'm curious whether it actually is)

**Comment by zjmiller** [comment]
It doesn't seem bad to me. This only occurs when a malicious expert declines to challenge at the topmost level. In this case, the entire tree ends before anything really happens anyway.

**Comment by zjmiller** [comment]
Should definitely have mentioned that after merging MIB PR #650 this will be fixed anyway.

**Comment by zjmiller** [comment]
This is because PR #650 resolves issue #664.

**Comment by zjmiller** [comment]
Resolved in #650
