### ISSUE TITLE
Add isolated workspace view (without navigation buttons)

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#72]
E.g. `/workspaces/d8757f60-7ba4-4af7-8d33-fe25b0cc42ae/standalone`. This way, the experiment manager can send this URL and the participants aren't constantly tempted to navigate to parents or children.

Only show "open", "to subtree", "to parent" in normal mode.

**Comment by stuhlmueller** [comment]
This view could also show a countdown timer, maybe paramterized by URL, e.g. `/workspaces/d8757f60-7ba4-4af7-8d33-fe25b0cc42ae/standalone/10m`.

**Comment by zjmiller** [comment]
This was merged to master in #168.
