### ISSUE TITLE
Make it possible to set the depth limit for an individual tree

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#732]
It's probably fine if it's only possible to set it for an experiment, but individual tree is preferable, so let's discuss if it's not possible to set it for individual trees.

The dev hours is what I remember @zjmiller saying once, obviously feel free to change it

**Comment by brachbach** [comment]
If it's per tree, we'd definitely want to be able to set or change it via the API

Not important to be able to set or change it via the UI IMO

**Comment by brachbach** [comment]
Is this issue now totally complete?

**Comment by zjmiller** [comment]
Resolved in #733
