### ISSUE TITLE
Be able to show arbitrary text (including hyperlinks) in every workspace of a tree

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#736]
The current primary motivation for this is to be able to link to a doc that specifies what strategy judges should use on the tree.

But we may want it for other things in the future.

We could do this as an extension of https://github.com/oughtinc/mosaic/issues/626 -- I'd be totally fine with something hacky like:
1. All text in the root-level stratchpad gets shown to experts
2. All text between, say < and > also gets shown to judges

**Comment by brachbach** [comment]
@william-r-s do you think this would accomplish what you were hoping re: associating a strategy with a tree?

Particularly, do you think it might be important at all to NOT allow experts to see the strategy doc that's shared with judges?

**Comment by brachbach** [comment]
(I'm guessing this would be relatively easy to do, at least if we do it the hacky rootScratchpad way)

**Comment by william-r-s** [comment]
I think that showing information to only judges is lower priority. We can always experiment with it on the honor system if we think it's useful, but it feels like for showing high level malicious play we'd want the strategy docs to be open to them, and if the malicious expert can look at judge spaces you'd need to make sure to only show it when assigned to the role.

**Comment by andrewschreiber** [comment]
> All text between, say < and > also gets shown to judges
@brachbach Do you mean text that is entered into the root-level scratchpad? I assume also that text would be available to non-judges.

**Comment by brachbach** [comment]
1. yes, text in the root-level scratchpad
2. yes, it should also be shown to non-judges

For what it's worth, I thought of a more principled way to do this. Instead of the marked-up text, the root scratchpad woudl be a JSON that looks like:

```
{
  "judge": "text that judge sees",
  "honestExpert": "text that Honest Expert sees",
  "maliciousExpert": "text that Malicious Expert can sees"
}
```

But problems with this include:
1. we then have to be able to show text to only each of the roles, rather than the default plan of just "only experts" and "everyone"
2. we'd need to migrate from the current system of "everything in root scratchpad shown to only experts" to this new JSON format

thought on whether some more principled thing like this JSON format is a good idea?

**Comment by andrewschreiber** [comment]
Hmm not sure, will take a closer look tomorrow. I think the 'nice' thing about the current approach is that we simply pass around the entire Slate block of the scratchpad, which lets us carry the pointers. With JSON, we'd need a different pointer approach.

**Comment by andrewschreiber** [comment]
Okay figured out how to do this using the existing `block` system (as in without refactoring to JSON). The block approach reflects the usual way that we pass text info around Mosaic1 and comes with the full suite of watchers, pointer integration, etc. Inclined to go with the devil-we-know here.

Here's what it'd look like. 
1. Expand the logic from #626 to include both judges and experts. Set up two logical paths.
2. We'd extract the text from the `block.value` using `listOfSlateNodesToText`, then regex checking the text for `< >`. 
   3a. In the expert case, we'd pass the original `block` regardless of the regex to the editor. 
   3b. In the judge case, we'd strip the non-matching text out of the string, convert it back into a `value` we can add to a `block` using the approach seen in `contentToSlateNodes`, then pass that new block to the editor.
4. Render the block in a read-only editor

**Comment by brachbach** [comment]
- re: 2 - `< >` was a totally random idea. If we're basically just using regex, then we're free to do it however we like. I think I'd suggest `<judge>_text for judge here_</judge>` (like HTML). Most importantly, I think you can then just render the entire contents of the root scratchpad to experts, and it'll be obvious to them that the `<judge>_text for judge here_</judge>` part is the part that judges get to see
- re: 3 - preserving pointers doesn't feel that important. Preserving links is fairly important

One more thought -- let's make sure that this text doesn't count against input bandwidth
