### ISSUE TITLE
Remove the ability to archive subquestions

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#737]
In vanilla FE, archiving is sort of confusing. IMO the main point of it is if you realize that you made an error in your subquestion and want to get rid of it before it gets assigned to anyone. That is, I don't think it makes much sense to archive a subquestion that's already received an answer.

In MIB, your judge assignment ends as soon as you ask a subquestion, and the workspace won't get assigned to someone else until the subquestion produces an answer. So, there's no good case for using archiving.

Given that it adds complication to the game and is generally confusing, I think we should just get rid of it (at least for now).

We could wait until we've fully rolled out MIB, but I don't think that's necessary because I don't think that archiving is very useful even in vanilla FE.

I'm guessing that removing the ability to archive would be extremely easy, since we can just remove the UI element. I think we probably don't want to put in the effort to remove all code related to archiving, especially since there's some chance we'll want to put it back in later.

**Comment by Mati-Roy** [comment]
@brachbach if it's easy to not remove the button for, and only for, the root question, that would be great to keep the ability to easily close trees that are broken. related: [Reporting broken trees](https://forum.ought.org/t/reporting-broken-trees/94)

**Comment by brachbach** [comment]
@Mati-Roy , why not just remove the tree from the experiment in that case? (or delete it entirely?)

**Comment by Mati-Roy** [comment]
@brachbach 
> @Mati-Roy , why not just remove the tree from the experiment in that case? (or delete it entirely?)

so that:
a) participants can do this procedure themselves
b) because it's easier/faster to do
c) to be able to analyze the trees as it might still have relevant info (shouldn't delete them)
d) to be able to make stats on the experiment (shouldn't remove trees from one)

**Comment by brachbach** [comment]
@Mati-Roy, when you say

> to not remove the button for, and only for, the root question

you're referring to the root workspace for the entire tree, right? (the workspace where the malicious expert or the API sets the root question)

**Comment by Mati-Roy** [comment]
yes! maybe I should call it differently (?)

**Comment by andrewschreiber** [comment]
The ideal deliverable for this issue is: hide the archive button on all questions except the root-level question. Correct summary?

**Comment by brachbach** [comment]
yep!

and we'd like to know how long you'd estimate that'd take :)

**Comment by andrewschreiber** [comment]
The code change was pretty simple but I'm still trying to figure out how to generate the exact scenarios to test the behavior.

**Comment by andrewschreiber** [comment]
Okay to be clear, what we're looking for is in this situation, only the 1st subquestion should show `archive`, correct?
![image](https://user-images.githubusercontent.com/1892071/65205949-ce93cc00-da42-11e9-9e3d-6f16a82ce87b.png)

**Comment by brachbach** [comment]
Hoping it will be less confusing with this fuller and more labeled screenshot:

<img width="1914" alt="Screen Shot 2019-09-18 at 9 34 09 PM" src="https://user-images.githubusercontent.com/16952006/65213716-21c64880-da5c-11e9-896d-ed1778a92253.png">

- this is https://mosaic.ought.org/w/10518?e=3bdd9aa8-a1f2-4991-8b11-d0b75a521cff
- everything here was created entirely through the UI
- this is the very first workspace anyone in the tree would ever see, if the experiment is created entirely via the UI (i.e. no top-level question provided)

This is the **one subquestion** that should be archivable

There should never be more than one subquestion here, so it doesn't matter whether or not the others would be archivable if there were somehow more than one (easier to just make them all archivable, I'd think)

**Comment by andrewschreiber** [comment]
Thanks, I think I'm honing in on the properties to check for. Is it fundamental that the archivable question comes from a malicious expert's workspace?

**Comment by andrewschreiber** [comment]
Whiteboard discussion. We only want to show the archive button on the very top left workspace (which must always be a malicious expert workspace)
![image](https://user-images.githubusercontent.com/1892071/65478271-fe294680-de3d-11e9-8913-8581534d60f4.png)
